# Spring相关配置
spring:
  # Profile相关配置
  profiles:
    # 激活哪些Profile配置
    active: dev
  # Jackson框架的相关配置
  jackson:
    # 响应的JSON结果中默认包含哪些属性
    default-property-inclusion: non_null

# 使用Mybatis时，配置SQL语句的XML文件的位置
mybatis:
  mapper-locations: classpath:mapper/*.xml

knife4j:
  enable: true