# ########################### #
# 当前文件中的是【生产环境】的配置 #
# ########################### #

# 连接数据库的配置
spring.datasource.url: jdbc:mysql://db.aliyun.com:3306/cmhservice_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Chongqing
spring.datasource.username: root
spring.datasource.password: root

# 日志的显示级别
logging.level.cn.tedu.csmall: warn