# ########################### #
# 当前文件中的是【开发环境】的配置 #
# ########################### #

# Web服务端口
server:
  port: 9080

# 连接数据库的配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cmhservice_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Chongqing
    username: root
    password: root

# 日志的显示级别
logging:
  level:
    edu.asnc.college.mhservice.system: trace

# 当前项目中的自定义配置
csmall:
  # JWT相关配置
  jwt:
    # 生成和解析JWT时使用的secretKey，此属性的值不得少于4个字符，建议在30~60字符之间，应该是一个不容易被猜测的值
    secret-key: fdsFOj4tp9Dgvfd9t45rDkFSLKgfR8ou
    # JWT的有效时长，以分钟为单位
    duration-in-minute: 10080